name: photometric-viewer
base: core22
adopt-info: photometric-viewer
confinement: strict

environment:
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
  
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  
apps:
  photometric-viewer:
    extensions:
      - gnome
    command: bin/photometric-viewer
    common-id: io.github.dlippok.photometric-viewer
    desktop: share/applications/io.github.dlippok.photometric-viewer.desktop
    plugs:
      - home
      - removable-media

parts:
  photometric-viewer:
    plugin: python
    source: .
    build-environment:
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""

    override-build: |
      make build
      INSTALL_TARGET=${CRAFT_PART_INSTALL} make install-dist
      snapcraftctl build

    override-stage: |
      sed -i 's|Icon=.*$|Icon=share/icons/hicolor/scalable/apps/io.github.dlippok.photometric-viewer.svg|g' ${CRAFT_PART_INSTALL}/share/applications/io.github.dlippok.photometric-viewer.desktop
      snapcraftctl stage

    stage:
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg

    parse-info:
      - share/metainfo/io.github.dlippok.photometric-viewer.metainfo.xml
