name: photometric-viewer # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: View IESNA and EULUMDAT photometric files. # 79 char long summary
description: |
    Photometic Viewer allows you to see following information from the opened photometric file:
  
    - Light distribution curves of selected photometric files
    - General information (Catalog Number, Manufacturer, Description, etc.)
    - Photometric properties (Light Output Ration and Downward Flux Fraction)
    - Lamps and ballast information
    - Luminaire and luminous opening geometry information
    - Additional properties (Test number, issue date, test laboratory, etc.)
    - Raw text source of photometric file

confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  photometric-viewer:
    extensions: [gnome]
    command: /snap/usr/bin/photometric-viewer
    plugs: [ home, removable-media ]

parts:
  photometric-viewer:
    plugin: python
    source: https://github.com/dlippok/photometric-viewer.git  # Install from a git repository
    source-tag: v0.2.0
    build-environment:
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
    override-prime: |
      mkdir /snap/usr
      cp -r /root/.local/* /snap/usr
      snapcraftctl prime
    parse-info: [usr/share/metainfo/io.github.dlippok.photometric-viewer.metainfo.xml]